---
domain: edeluquez.com

environments:
  dev:
    zones_numbers: 4
    regions: "us-east-1"
    cidr: "172.0.0.0/16"
    cidr_subnet_bits: 7
    high_availability: true

  qa:
    zones_numbers: 2
    regions: "us-east-1"
    cidr: "174.0.0.0/16"
    cidr_subnet_bits: 8
    high_availability: false
