---
project: ftva
domain: .com

environments:
  dev:
    cloud:
      provider: aws
      region: us-east-1
      account_id:

    networking:
      cidr: "10.18.0.0/16"
      zones_numbers: 2
      cidr_subnet_bits: 6
      high_availability: false
      subnets:
        private: true
        public: true
        database: true

    hosts:
      size: 30
      name: bastion
      wakeup: true
      type: t4g.nano
      distro: debian

    security:
      ip_access_allow: [""]
      ssh_keys:
        - ssh-rsa
        - ssh-ed25519
...
