---
name: Deploy Infrastructure
run-name: Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'fix/*'
      - 'feat/*'
      - 'feature/*'
    paths:
      - '*.tf'
      - 'templates/*.*'
      - 'modules/*/*.tf'
      - 'config.yaml'
      - 'config.yaml.j2'

jobs:
  setup-env:
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: dev
      AWS_REGION: ${{ vars.AWS_REGION }}

    steps:
      - name: echo
        run: |
          echo "AWS_REGION=${{ vars.AWS_REGION }}"
          echo "${{ secrets.DOMAINNAME }}${{ secrets.AWS_ROLE_ARN }}${{ secrets.AWS_ACCOUNT_ID }}${{ secrets.AWS_S3_BACKEND }}${{ secrets.AWS_S3_BACKEND_KEY }}"

  deploy:
    needs: setup-env
    uses: edelux/terraform-template/.github/workflows/deploy.yaml@main
    with:
      AWS_REGION: ${{ needs.setup-env.outputs.AWS_REGION }}
      ENVIRONMENT: ${{ needs.setup-env.outputs.ENVIRONMENT }}
    secrets:
      DOMAINNAME: ${{ secrets.DOMAINNAME }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_S3_BACKEND: ${{ secrets.AWS_S3_BACKEND }}
      AWS_S3_BACKEND_KEY: ${{ secrets.AWS_S3_BACKEND_KEY }}

    permissions:
      id-token: write
      contents: read
